pragma ComponentBehavior: Bound

import qs.config
import qs.services
import Quickshell.Io
import QtQuick

// Data + persistence backend for the emoji launcher plugin. Non-singleton
// (only the launcher consumes it) — instantiated inside EmojiModule. Loads the
// bundled `emojis.txt` (tab-separated `emoji \t group \t name \t keywords`,
// generated by scripts/gen_emoji_data.py from the canonical Unicode
// emoji-test.txt) and keeps a persisted "recently used" list in
// `${Paths.state}/emoji-recents.json`.
QtObject {
    id: root

    // Parsed dataset. Each: { emoji, group, name, keywords, search }.
    property var all: []
    // Category names in canonical (first-appearance) order.
    property var groups: []
    property bool loaded: false

    // Recently-used emoji chars, most-recent first (persisted).
    property var recents: []
    property bool recentsLoaded: false
    readonly property int recentsLimit: Config.getCustom("emoji", "recentsLimit", 48) ?? 48

    // Sentinel group id for the recents tab.
    readonly property string recentGroup: "__recent__"

    function _parse(text) {
        const lines = text.split("\n");
        const arr = [];
        const seen = [];
        for (const line of lines) {
            if (!line)
                continue;
            const f = line.split("\t");
            if (f.length < 3)
                continue;
            const group = f[1];
            if (seen.indexOf(group) < 0)
                seen.push(group);
            arr.push({
                emoji: f[0],
                group,
                name: f[2],
                keywords: f[3] ?? "",
                search: (f[2] + " " + (f[3] ?? "")).toLowerCase()
            });
        }
        root.all = arr;
        root.groups = seen;
        root.loaded = true;
    }

    // Entries to show for the current query/group. A non-empty query searches
    // the whole set (AND over space-split terms); otherwise filter by group
    // (or the recents list).
    function filter(query, group) {
        const q = (query ?? "").trim().toLowerCase();
        if (q) {
            const terms = q.split(/\s+/);
            return root.all.filter(e => terms.every(t => e.search.indexOf(t) >= 0));
        }
        if (group === root.recentGroup)
            return root.recentList();
        if (group)
            return root.all.filter(e => e.group === group);
        return root.all;
    }

    function recentList() {
        const byChar = ({});
        for (let i = 0; i < root.all.length; i++)
            byChar[root.all[i].emoji] = root.all[i];
        return root.recents.map(c => byChar[c] ?? {
            emoji: c,
            group: "",
            name: c,
            keywords: "",
            search: ""
        });
    }

    function pushRecent(emoji) {
        let next = root.recents.filter(c => c !== emoji);
        next.unshift(emoji);
        if (next.length > root.recentsLimit)
            next = next.slice(0, root.recentsLimit);
        root.recents = next;
        recentsSave.restart();
    }

    onRecentsChanged: if (recentsLoaded) recentsSave.restart()

    // ── Bundled dataset (read-only) ───────────────────────────────────
    property FileView _data: FileView {
        path: Qt.resolvedUrl("emojis.txt")
        onLoaded: root._parse(text())
        onLoadFailed: err => console.warn("[Emoji] failed to load emojis.txt:", err)
    }

    // ── Recents (persisted) ───────────────────────────────────────────
    property Timer _recentsSave: Timer {
        id: recentsSave
        interval: 400
        onTriggered: recentsStore.setText(JSON.stringify(root.recents))
    }

    property FileView _recentsStore: FileView {
        id: recentsStore
        path: `${Paths.state}/emoji-recents.json`
        onLoaded: {
            let data = [];
            try {
                data = JSON.parse(text());
            } catch (e) {
                data = [];
            }
            root.recents = Array.isArray(data) ? data : [];
            root.recentsLoaded = true;
        }
        onLoadFailed: err => {
            if (err === FileViewError.FileNotFound) {
                root.recentsLoaded = true;
                setText("[]");
            }
        }
    }
}
