exec-once=~/.config/quickshell/pShell/scripts/walltool/target/release/walltool
exec-once=awww-daemon
windowrule = float on, match:title ^(pShell Settings)$
windowrule = center on, match:title ^(pShell Settings)$
bind = SUPER, R, global, pShell:launcher
bind = SUPER SHIFT, B, global, pShell:bar
bind = SUPER, I, global, pShell:settings
# bind = $mainMod SHIFT, comma, exec, matugen --type scheme-neutral image "$(find ~/Pictures/Wallpapers -maxdepth 1 -type f | shuf -n 1)"
