pragma Singleton

import qs.config
import Quickshell
import Quickshell.Io
import QtQuick

// Drives niri's compositor blur for the shell's main layer (`pShell-drawers`)
// by (re)writing a small kdl file that the user `include`s from their niri
// config. niri has no runtime IPC to add/remove layer-rules, so the toggle
// lives in the included file instead; niri reloads it on change.
//
// User-side setup (once), in ~/.config/niri/config.kdl:
//   include "~/.config/quickshell/pShell/config/niri/blur.kdl"
Singleton {
    id: root

    readonly property string kdlPath: `${Quickshell.env("HOME")}/.config/quickshell/pShell/config/niri/blur.kdl`

    readonly property string header: "// Generated by pShell (utils/NiriBlur.qml) — do not edit by hand.\n"
        + "// Toggled from Settings → General → Transparency & blur.\n"
        + "// Include this file from your niri config, e.g.:\n"
        + "//   include \"~/.config/quickshell/pShell/config/niri/blur.kdl\"\n"

    function _content(on: bool): string {
        if (!on)
            return header + "// pShell blur: disabled\n";
        return header + `layer-rule {
    match namespace="^pShell-drawers$"
    background-effect {
        blur true
    }
}
`;
    }

    function write(): void {
        const fv = _fileComp.createObject(root, { path: kdlPath, atomicWrites: true, printErrors: true });
        if (!fv)
            return;
        fv.setText(_content(Config.general.transparency.blur));
        Qt.callLater(() => fv.destroy());
    }

    // Keep the file in sync with the config flag; write once at startup so a
    // fresh checkout (or a flag flipped while the shell was down) is reflected.
    Component.onCompleted: write()

    Connections {
        target: Config.general.transparency
        function onBlurChanged(): void {
            root.write();
        }
    }

    Component {
        id: _fileComp
        FileView {}
    }
}
